# Generated by Django 3.1.4 on 2020-12-07 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Basic', '0002_auto_20201207_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='markdetails',
            old_name='user_id',
            new_name='user',
        ),
    ]
