# Generated by Django 3.1.4 on 2020-12-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic', '0004_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
            ],
        ),
    ]
