# Generated by Django 3.1.4 on 2020-12-09 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Basic', '0005_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markdetails',
            name='semester',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Basic.semester'),
        ),
        migrations.CreateModel(
            name='additionalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Basic.departments')),
                ('current_semester', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Basic.semester')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
