# Generated by Django 3.1.4 on 2020-12-09 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Basic', '0006_auto_20201209_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markdetails',
            name='Department',
        ),
    ]
