# Generated by Django 3.1.4 on 2020-12-09 13:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Basic', '0007_remove_markdetails_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='current_semester',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Basic.semester', validators=[django.core.validators.MaxValueValidator(101)]),
        ),
        migrations.AlterField(
            model_name='markdetails',
            name='marks',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(101)]),
        ),
        migrations.AlterField(
            model_name='markdetails',
            name='semester',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(12)]),
        ),
    ]
