# Generated by Django 3.1.4 on 2020-12-15 05:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic', '0008_auto_20201209_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalinfo',
            name='privacy',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1)]),
        ),
    ]
